/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ErrorCode = string;
export type AwsArnString = string;
export type AwsCfInstruction = string | AwsCfFunction;
export type AwsCfFunction = AwsCfImport | AwsCfJoin | AwsCfGetAtt | AwsCfRef | AwsCfSub;

export interface AWS {
  service: {
    name?: {
      [k: string]: unknown;
    };
    awsKmsKeyArn?: {
      [k: string]: unknown;
    };
  };
  frameworkVersion?: string;
  disabledDeprecations?:
    | {
        [k: string]: unknown;
      }
    | ErrorCode
    | ErrorCode[];
  enableLocalInstallationFallback?: boolean;
  custom?: {
    enterprise?: {
      collectApiGatewayLogs?: boolean;
      collectLambdaLogs?: boolean;
      compressLogs?: boolean;
      disableAwsSpans?: boolean;
      disableFrameworkInstrumentation?: boolean;
      disableHttpSpans?: boolean;
      logAccessIamRole?: AwsArnString;
      logIngestMode?: "push" | "pull";
    };
    safeguards?: {
      isDisabled?: boolean;
    };
    [k: string]: unknown;
  };
  plugins?: string[];
  functions?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9-_]+$".
     */
    [k: string]: {
      name?: string;
      events?: (
        | {
            __schemaWorkaround__: {
              [k: string]: unknown;
            };
          }
        | {
            schedule:
              | string
              | {
                  rate: string;
                  enabled?: boolean;
                  name?: string;
                  description?: string;
                  input?:
                    | string
                    | (
                        | {
                            body: string;
                          }
                        | {
                            [k: string]: unknown;
                          }
                      );
                  inputPath?: string;
                  inputTransformer?: {
                    inputTemplate: string;
                    inputPathsMap?: {
                      [k: string]: unknown;
                    };
                  };
                };
          }
        | {
            s3:
              | string
              | {
                  [k: string]: unknown;
                };
          }
        | {
            http:
              | string
              | {
                  [k: string]: unknown;
                };
          }
        | {
            websocket:
              | string
              | {
                  [k: string]: unknown;
                };
          }
        | {
            sns:
              | string
              | AwsArnString
              | (
                  | {
                      [k: string]: unknown;
                    }
                  | {
                      [k: string]: unknown;
                    }
                );
          }
        | {
            stream:
              | string
              | {
                  [k: string]: unknown;
                };
          }
        | {
            alb: {
              [k: string]: unknown;
            };
          }
        | {
            alexaSkill:
              | string
              | {
                  [k: string]: unknown;
                };
          }
        | {
            alexaSmartHome:
              | string
              | {
                  [k: string]: unknown;
                };
          }
        | {
            iot: {
              sql: string;
              sqlVersion?: "2015-10-08" | "2016-03-23" | "beta";
              name?: string;
              enabled?: boolean;
              description?: string;
            };
          }
        | {
            cloudwatchEvent: {
              [k: string]: unknown;
            };
          }
        | {
            cloudwatchLog:
              | string
              | {
                  [k: string]: unknown;
                };
          }
        | {
            cognitoUserPool: {
              pool: string;
              trigger:
                | "PreSignUp"
                | "PostConfirmation"
                | "PreAuthentication"
                | "PostAuthentication"
                | "PreTokenGeneration"
                | "CustomMessage"
                | "DefineAuthChallenge"
                | "CreateAuthChallenge"
                | "VerifyAuthChallengeResponse"
                | "UserMigration";
              existing?: boolean;
            };
          }
        | {
            eventBridge: (
              | {
                  [k: string]: unknown;
                }
              | {
                  [k: string]: unknown;
                }
            ) &
              (
                | {
                    [k: string]: unknown;
                  }
                | {
                    [k: string]: unknown;
                  }
                | {
                    [k: string]: unknown;
                  }
                | {
                    [k: string]: unknown;
                  }
              );
          }
        | {
            sqs:
              | string
              | {
                  [k: string]: unknown;
                };
          }
        | {
            cloudFront: {
              [k: string]: unknown;
            };
          }
        | {
            httpApi:
              | string
              | {
                  authorizer?:
                    | string
                    | (
                        | {
                            [k: string]: unknown;
                          }
                        | {
                            [k: string]: unknown;
                          }
                      );
                  method?: string;
                  path: string;
                };
          }
      )[];
      handler?: string;
      fileSystemConfig?: {
        localMountPath: string;
        arn: string;
      };
      [k: string]: unknown;
    };
  };
  provider: {
    name: {
      [k: string]: unknown;
    };
    httpApi?: {
      authorizers?: {
        [k: string]: {
          name?: string;
          identitySource: AwsCfInstruction;
          issuerUrl: AwsCfInstruction;
          audience: AwsCfInstruction | AwsCfInstruction[];
        };
      };
      cors?:
        | boolean
        | {
            allowedOrigins?: string | string[];
            allowedHeaders?: string | string[];
            allowedMethods?: string | string[];
            allowCredentials?: boolean;
            exposedResponseHeaders?: string | string[];
            maxAge?: number;
          };
      id?: string | AwsCfImportLocallyResolvable;
      name?: string;
      payload?: string;
    };
    logs?: {
      httpApi?:
        | boolean
        | {
            format?: string;
          };
      [k: string]: unknown;
    };
    resourcePolicy?: {
      [k: string]: unknown;
    }[];
    stage?: string;
    variableSyntax?: string;
    [k: string]: unknown;
  };
  package?: {
    individually?: boolean;
    path?: string;
    artifact?: string;
    exclude?: string[];
    include?: string[];
    excludeDevDependencies?: boolean;
  };
  layers?: {
    [k: string]: unknown;
  };
  configValidationMode?: "error" | "warn" | "off";
  resources?: {
    AWSTemplateFormatVersion?: string;
    Description?: string;
    Metadata?: {
      [k: string]: unknown;
    };
    Parameters?: {
      [k: string]: unknown;
    };
    Mappings?: {
      [k: string]: unknown;
    };
    Conditions?: {
      [k: string]: unknown;
    };
    Transform?: {
      [k: string]: unknown;
    };
    Resources?: {
      /**
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "^[a-zA-Z0-9]{1,255}$".
       */
      [k: string]: {
        Properties?: {
          [k: string]: unknown;
        };
        CreationPolicy?: {
          [k: string]: unknown;
        };
        DeletionPolicy?: string;
        DependsOn?: string[];
        Metadata?: {
          [k: string]: unknown;
        };
        UpdatePolicy?: {
          [k: string]: unknown;
        };
        UpdateReplacePolicy?: string;
        Condition?: string;
        [k: string]: {
          [k: string]: unknown;
        };
      };
    };
    extensions?: {
      /**
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "^[a-zA-Z0-9]{1,255}$".
       */
      [k: string]: {
        Properties?: {
          [k: string]: unknown;
        };
        CreationPolicy?: {
          [k: string]: unknown;
        };
        DeletionPolicy?: string;
        DependsOn?: string[];
        Metadata?: {
          [k: string]: unknown;
        };
        UpdatePolicy?: {
          [k: string]: unknown;
        };
        UpdateReplacePolicy?: string;
        Condition?: string;
      };
    };
    Outputs?: {
      [k: string]: unknown;
    };
  };
  org?: string;
  app?: string;
  outputs?: {
    [k: string]:
      | string
      | number
      | boolean
      | unknown[]
      | {
          [k: string]: unknown;
        };
  };
}
export interface AwsCfImport {
  "Fn::ImportValue": unknown;
}
export interface AwsCfJoin {
  "Fn::Join": [string, unknown[]];
}
export interface AwsCfGetAtt {
  "Fn::GetAtt": string[];
}
export interface AwsCfRef {
  Ref: string;
}
export interface AwsCfSub {
  "Fn::Sub": unknown;
}
export interface AwsCfImportLocallyResolvable {
  "Fn::ImportValue": string;
}
