name: Tests
on:
  push

jobs:
  tests:
    name: Run serverless/typescript tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm i

      - name: Run lint tests
        run: npm run test:lint

      - name: Run type tests
        run: npm run test:type
