name: Update and Release Serverless Definitions
on:
  workflow_dispatch:
  repository_dispatch:
    types: [serverless-released]

jobs:
  generateTSDefinitions:
    name: Generate serverless/serverless typescript definitions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm i

      - name: Build plugin
        run: npm run build

      - name: Set Serverless latest version
        id: serverless-version
        run: |
          version=$(npm list serverless | grep serverless@ | sed 's/.*serverless@/v/g' | tr -d '[[:space:]]')
          echo "version=$version" >> $GITHUB_ENV

      - name: Generate TypeScript Definitions
        run: npx sls schema
        env:
          SERVERLESS_ACCESS_KEY: ${{secrets.SERVERLESS_ACCESS_KEY}}

      - name: Update package.json version
        run: npm version ${{ env.version }} --git-tag-version=false

      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          author_name: Eslam Î» Hefnawy
          author_email: eslam@serverless.com
          branch: master
          message: Add Serverless definitions for ${{ env.version }}
          add: index.d.ts package.json
          tag: ${{ env.version }} --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
